# This is an example of a DRO parameters file
# It is written according to the YAML-convention (www.yaml.org) and is checked by the code for consistency.
# All parameters are entered as part of a dictionary 
# Users enter their desired minimum, maximum, and number of values (in that order)
# If users desire default values, the entry can be left blank. 
# If the entry is removed from the parameter list, it is also converted to default values
 
parameters:
#   # Size Features
    mean_radius: [20, 100, 2]
#   # Shape Features
#   x_deformation:
#   y_deformation:
#   z_deformation:
    surface_frequency: [9, 9, 1]
    surface_amplitude: [0,0.2, 2]
#   # Intensity Features
    mean_intensity: [-100, 100, 2]
#   # Texture Features
    texture_wavelength: [10,10,1]
    texture_amplitude: [0, 50.0, 2]
#   # Margin Features
    gaussian_standard_deviation: [0, 10, 2]
